### ISSUE TITLE
CLI worker `arg.type` error 

### ISSUE THREAD

**Issue by mahdi13** [pylover/restfulpy#84]
@pylover  
I got exception here:
```
  File "/home/.../.virtualenvs/.../lib/python3.5/site-packages/restfulpy/cli/base.py", line 25, in __call__
    self.launch()
  File "/home/.../.virtualenvs/.../lib/python3.5/site-packages/restfulpy/cli/main.py", line 47, in launch
    cli_args.func(cli_args)
  File "/home/.../.virtualenvs/.../lib/python3.5/site-packages/restfulpy/cli/base.py", line 25, in __call__
    self.launch()
  File "/home/.../.virtualenvs/.../lib/python3.5/site-packages/restfulpy/cli/worker.py", line 43, in launch
    print('|'.join(self.args.type) or 'all types!')
AttributeError: 'Namespace' object has no attribute 'type'

```
when I execute this:
```
... worker start 
```

I think it's reason is you removed the `type` arg but you didn't remove this line:
```
print('|'.join(self.args.type) or 'all types!')
```

**Comment by mahdi13** [comment]
Server is working fine, but in local I got this exception:
```
2017-07-30 18:28:09 - taskqueue - INFO - No task to pop: {'type': "<class 'restfulpy.taskqueue.TaskPopError'>", 'content': 'There is no task to pop'}
INFO:taskqueue:No task to pop: {'type': "<class 'restfulpy.taskqueue.TaskPopError'>", 'content': 'There is no task to pop'}
Exception in thread restfulpy-worker-thread-0:
Traceback (most recent call last):
  File "/home/perfect/.virtualenvs/pavo/lib/python3.5/site-packages/restfulpy/taskqueue.py", line 124, in worker
    task.execute(context)
AttributeError: 'NoneType' object has no attribute 'execute'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/perfect/.virtualenvs/pavo/lib/python3.5/site-packages/restfulpy/taskqueue.py", line 131, in worker
    logger.exception('Error when executing task: %s' % task.id)
AttributeError: 'NoneType' object has no attribute 'id'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/home/perfect/.virtualenvs/pavo/lib/python3.5/site-packages/restfulpy/taskqueue.py", line 138, in worker
    tasks.append((task.id, task.status))
AttributeError: 'NoneType' object has no attribute 'id'

```
